### ISSUE TITLE
Request support for Chinese language option

### ISSUE THREAD

**Issue by hao-lh** [AlexanderWillner/deepl-alfred-workflow2#10]
Hi there,

Thanks so much for offer this workflow which would simply language translation with Alfred. 

But I did't know how to make it translate English into Chines? As Readme indicated, I should set $DEEPL_TARGET variable when import the workflow for the first time, I also noticed this workflow seemed to be based on https://github.com/m9dfukc/deepl-alfred-workflow, but Chinese language seemed not among the list: de, en, fr, es, it, nl, pl

Could you help add this option, thank you so much!

**Comment by AlexanderWillner** [comment]
Actually, never found a reliable way to talk with the DeepL API w/o being blocked sooner or later. Have you considered to use https://www.deepl.com/app/ instead?

**Comment by hao-lh** [comment]
Hi Alex, thanks for your feedback.
The problem is DeepL app does not support legacy macOS 10.11 El Capitan, that's why I seek to workflow as an alternative.

**Comment by jilulu** [comment]
Just set environment variable to `ZH` and it should work with no further action required.

**Comment by AlexanderWillner** [comment]
yes, seems to work better now
