### ISSUE TITLE
„jq-dist“ OSX permisison error

### ISSUE THREAD

**Issue by t-io** [AlexanderWillner/deepl-alfred-workflow2#17]
There is an issue using this workflow after installing it, like described. 

<img width="409" alt="Bildschirmfoto 2021-07-05 um 13 50 48" src="https://user-images.githubusercontent.com/1128363/124467874-bb2d2e80-dd98-11eb-937a-bec24bd9c371.png">

To use this workflow anyway, click show in finder and right click and open the jq-dist file. Once done, the workflow works like intended. I suggest updating the installation instructions.

**Comment by AlexanderWillner** [comment]
Yes, indeed, this is an issue:

- What you can do (once): "Im Finder zeigen" > "Rechte Maustaste" > "Öffnen" > "OK"
- What I can do: sign the binary with my developer certificate

**Comment by AlexanderWillner** [comment]
Seems I already signed the binary in version `Release 1.41 (2021-02-24)` - is this the version you've also troubles with?

```
 % codesign -vv jq-dist 
jq-dist: valid on disk
jq-dist: satisfies its Designated Requirement
```

**Comment by t-io** [comment]
Yes, indeed. I got this issue with 1.41.

**Comment by Juuro** [comment]
Some here! I get the same error, also with the latest version (1.41).

**Comment by AlexanderWillner** [comment]
can you test the latest release?

**Comment by krns** [comment]
I had the same problem with the old version. Seems to be fixed now.

**Comment by AlexanderWillner** [comment]
Thanks!
