### ISSUE TITLE
Issue: Invalid request for Chinese letters

### ISSUE THREAD

**Issue by manavortex** [AlexanderWillner/deepl-alfred-workflow2#19]
Hey there, 

first of all, thank you for maintaining this. It works fine if I stick to the preconfigured languages.

However, I've run into an issue with "打掛"  - which translates fine if I use the website: 
![image](https://user-images.githubusercontent.com/965785/158019525-f1519228-9919-480a-aa69-991f3746f935.png)

I've tried to poke at the shell script a little, but haven't been able to get it working. Presumably, it's an encoding problem. Could you look into it at some point?

Thank you!

**Comment by CoffeeDrinkRabbit** [comment]
进入Environment Variables设置界面，把DEEPL_PREFERRED里改成“ZH”，“EN”就可以了。

**Comment by AlexanderWillner** [comment]
Thanks, I assume this fixes it.
