### ISSUE TITLE
With a pro account, where do I configure the API key?

### ISSUE THREAD

**Issue by shaack** [AlexanderWillner/deepl-alfred-workflow2#20]
Thanks for the nice work. One question, I have a Deepl pro account, but where do I put the API key?

**Comment by shaack** [comment]
I have a Deepl pro account, but where do I put the API key?

**Comment by AlexanderWillner** [comment]
Good idea! I forgot about the API and just extended the workflow and documentation. Let me know if this works for you.

**Comment by shaack** [comment]
![Bildschirmfoto 2022-09-13 um 18 05 03](https://user-images.githubusercontent.com/832120/189951518-4224d23a-72c9-470c-8a10-649ccd2aa2d7.png)
Seems to work! 👍 Nice, thank you for the fast fixing.
