### ISSUE TITLE
【feature request】Period/Dot as variable

### ISSUE THREAD

**Issue by suliveevil** [AlexanderWillner/deepl-alfred-workflow2#21]
Chinese Period `。` is different from English `.`.
Would you please set dot as variable so we can customize it?
Thank you very much! 🥰

**Comment by AlexanderWillner** [comment]
Was a mitigation for #5 - but with #20 this is already disabled in the local version when the API key is set. Would this work for you?

**Comment by suliveevil** [comment]
DeepL haven't support Chinese user signup for API, So I couldn't have some more config choices.

When translate a sentence, I have to switch Input Method to input the endpoint `.`(In Chinese, `。` corresponds to `.`):
Instead of `世界你好。`, I should input `世界你好.` (`Hello World.`) to make this workflow works.

Or maybe I should add an action to replace the character. 🤣

**Comment by AlexanderWillner** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/307605/190847988-4df32a6d-22c1-48c7-87a9-d8927cba4629.png">

**Comment by suliveevil** [comment]
Great work, thank you very much. 🥰
