### ISSUE TITLE
Last character is removed in the translation

### ISSUE THREAD

**Issue by jvdmeij** [AlexanderWillner/deepl-alfred-workflow2#25]
See the video below.

Steps to reproduce: 
- Type `dl this is a test`
- Translation (to Dutch) will be `dit is een tes` instead of `dit is een test`
- Type `dl this is a test.`
- Translation (to Dutch) will be `dit is een test` instead of `dit is een test.`

https://user-images.githubusercontent.com/7727264/210106135-be374259-dc8c-4e4c-97ea-743f211068eb.mp4

**Comment by AlexanderWillner** [comment]
Indeed, this is probably an issue after solving #21 or #20
