### ISSUE TITLE
The original icon is not well recognized on dark skin, I replaced a new icon so that the user experience is better

### ISSUE THREAD

**Issue by HereOrCode** [AlexanderWillner/deepl-alfred-workflow2#26]
### icon
![icon](https://user-images.githubusercontent.com/83153991/215229610-71cc166f-55a3-477b-acec-3b0bd550e8b5.png)

### preview
<img width="718" alt="CleanShot 2023-01-28 at 08 27 02@2x" src="https://user-images.githubusercontent.com/83153991/215229750-b0332ef0-8bef-4a1c-bc9e-afce5f621568.png">

![image](https://user-images.githubusercontent.com/83153991/215229849-ef3c2dac-9338-403c-8c0f-281336c1ff4e.png)

### Download the icon
[icon.png.zip](https://github.com/AlexanderWillner/deepl-alfred-workflow2/files/10523999/icon.png.zip)

**Comment by AlexanderWillner** [comment]
Thanks! Just adopted it. Will be part of a future release.
