### ISSUE TITLE
Configurable target language

### ISSUE THREAD

**Issue by alexreg** [AlexanderWillner/deepl-alfred-workflow2#27]
Hello, would you kindly consider adding the feature to configure the target language with each command? For example:

> dl es Hello

(Translate from default source language to Spanish.)

> dl fr>es Hello

(Translate from French to Spanish.)

This would be very useful for users like myself who regularly translate to more than one target language.

Incidentally, what is "preferred languages" in the configuration? I haven't seen this documented anywhere.

**Comment by AlexanderWillner** [comment]
Now implemented via `dll` command.
