### ISSUE TITLE
Error: Invalid API Key

### ISSUE THREAD

**Issue by Chromagram** [AlexanderWillner/deepl-alfred-workflow2#31]
I've checked my API key several times, it's the same one I've always used until my previous DeepL workflow started returning errors. This one was recently updated so I was hoping to jump to using it. However, all it does is keep returning "Error: Invalid API Key".

I'm on an M2 Pro MacBook Pro, if that makes a difference, running it on Alfred 5. Any ideas possibly on why this is happening? Thank you!

**Comment by AlexanderWillner** [comment]
Oh, this might got introduced in #29 …

**Comment by Chromagram** [comment]
Thanks, I tried several times to renew the API key on DeepL and reinstalling the workflow with a new key, it just continues to return "Error: Invalid API Key" on any translation attempt.

**Comment by AlexanderWillner** [comment]
Do you know how to get the debug information? Alfred > Settings > Workflow > Deep-Translate > Toggle debugging mode (⌘D)

How it looks like here with an API key configured:

```
[15:29:54.535] Deepl-Translate[Script Filter] Queuing argument 'Key'
[15:29:54.987] Deepl-Translate[Script Filter] Script with argv '(null)' finished
[15:29:54.992] STDERR: Deepl-Translate[Script Filter] curl -s -X POST 'https://api-free.deepl.com/v2/translate' -H 'Authorization: DeepL-Auth-Key 11111111-1111-1111-1111-111111111111:fx' -d 'text=Key' -d 'target_lang=de'
[15:29:54.993] Deepl-Translate[Script Filter] {
  "items": [
    {
      "title": "Schlüssel",
      "arg": "Schlüssel"
    }
  ]
}
```

The result:

<img width="605" alt="image" src="https://github.com/AlexanderWillner/deepl-alfred-workflow2/assets/307605/447b530a-ac27-484b-928d-f2bca2d9c3eb">

**Comment by AlexanderWillner** [comment]
closing due to missing feedback
