### ISSUE TITLE
Error setting swedish as target language

### ISSUE THREAD

**Issue by panomitrius** [AlexanderWillner/deepl-alfred-workflow2#32]
![Skärmavbild 2024-01-25 kl  22 10 36](https://github.com/AlexanderWillner/deepl-alfred-workflow2/assets/75156060/5315326a-4e63-4fa1-80ec-bd55d7d9e715)
⬆️ These settings works fine.

![Skärmavbild 2024-01-25 kl  22 09 29](https://github.com/AlexanderWillner/deepl-alfred-workflow2/assets/75156060/c9915a10-0042-485f-a71d-50802721bd42)
⬆️ But these settings just generate an "Error" output message.

**Comment by AlexanderWillner** [comment]
Swedish is `sv`. See https://developers.deepl.com/docs/resources/supported-languages

<img width="605" alt="image" src="https://github.com/user-attachments/assets/103d26f0-bf39-4a3f-8991-db67c007246a">
