### ISSUE TITLE
Using "&" in sentence to be translated.

### ISSUE THREAD

**Issue by gmdelisle** [AlexanderWillner/deepl-alfred-workflow2#33]
Don't know if this is a bug or planned behaviour.

Anywhere I have "&" in my query the translation ends. 

See image for example.

![SCR-20240204-mofy](https://github.com/AlexanderWillner/deepl-alfred-workflow2/assets/39561162/d9ab42a2-ce91-463e-b862-e68532441c18)

**Comment by AlexanderWillner** [comment]
Thank you! Fixed.
