### ISSUE TITLE
Formality should be a Popup Selection (i.e. dropdown)

### ISSUE THREAD

**Issue by vitorgalvao** [AlexanderWillner/deepl-alfred-workflow2#37]
Looks like the new formality configuration can only be one of a defined set of values. That means it should be a Popup Selection, as opposed to a Text Field.

**Comment by AlexanderWillner** [comment]
Any documentation / example on how to define a dropdown? Seems Alfred just does not import the workflow if defining it like this:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/f3452578-9729-467c-bc55-bbd57b02ff7d">

**Comment by vitorgalvao** [comment]
You should never edit the info.plist manually. You add a Popover Button the same way you add the Text Fields: Click the [x] → Configuration Builder → Click the [+] on the bottom right.

It’s regular [Workflow Configuration](https://www.alfredapp.com/help/workflows/workflow-configuration/).

On that same vein, the languages should probably be something like a collection of checkboxes. The user configurations shouldn’t be treated as just a new textual interface for Workflow Environment Variables, they do much more in a much more pleasant and understandable interface for users.

If you have trouble with the process as described above, let me know and I can help.

**Comment by AlexanderWillner** [comment]
Funny, I think I never used the Configuration Builder or forgot about it :D
