### ISSUE TITLE
gunzip: unknown compression format

### ISSUE THREAD

**Issue by confluencepoint** [AlexanderWillner/deepl-alfred-workflow2#4]
Das Script meldet folgenden Fehler: `gunzip: unknown compression format`

curl: 7.43.0
jq: 1.6
Scheint ein API-Problem zu sein.
In Ref: https://github.com/m9dfukc/deepl-alfred-workflow/issues/14#issuecomment-447821435

**Comment by AlexanderWillner** [comment]
Thanks for the feedback. I removed ```gunzip``` last year to avoid this error message. I've now updated the downloadable workflow as well. So please test the latest version.

**Comment by confluencepoint** [comment]
Thanks. Works for me!
