### ISSUE TITLE
Workflow doesn't seem to work.

### ISSUE THREAD

**Issue by gbstan** [AlexanderWillner/deepl-alfred-workflow2#6]
Here is the debug message in the Alfred console debugger that is received for any query:

Code 127: [redacted]/deepl.sh: line 96: ./jq-dist: No such file or directory

Is there something missing?

**Comment by AlexanderWillner** [comment]
Is this with the latest version that you can download from https://github.com/AlexanderWillner/deepl-alfred-workflow2/raw/master/Deepl-Translate.alfredworkflow ?

**Comment by gbstan** [comment]
No, the version I tried was from packal.

This one seems to work.

**Comment by AlexanderWillner** [comment]
Thanks, will update the packal version then.
