### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by setegonz** [AlexanderWillner/deepl-alfred-workflow2#7]
The workflow doesn't seem to work when translating from Spanish to English. Do I need to configure something for this specific case? Since the default language is EN I didn't change anything in the configuration.

Thanks for your workflow!

**Comment by AlexanderWillner** [comment]
Mh, I see. So for example query for ```El tiempo es una ilusión```...

**Comment by setegonz** [comment]
@AlexanderWillner 
![8C5812F6-D3BD-4F2E-ADE7-3FEA10FA35E1](https://user-images.githubusercontent.com/11341688/57973416-0a2c6580-797f-11e9-92a7-28ebb687bf8f.png)

**Comment by politicus** [comment]
Close to the previous case. Just installed the workflow. Didn't change any variable.

When I use the "dl" keyword the word I type is translated to French.

When I use the "dlde" keyword the word I type is translated to de while the variable DEEPL_TARGET is set EN.

**Comment by ww7** [comment]
It's not send variable to that run mode
Probably not set or run in different env
I check manually in terminal
```
DEEPL_TARGET="RU"
./deepl.sh -l $DEEPL_TARGET "This is just an example."
```
– works

Hardcode  `dl` lang is works too

**Comment by AlexanderWillner** [comment]
```
It's not send variable to that run mode
Probably not set or run in different env
```
Fixed.
